database:
  database: //
  hostname: //
  username: //
  password: //

settings:
  crate-per-day: 10
  crate-delay: 10 #seconds
  max-crate-items: 12

animation:
  - "GREEN_STAINED_GLASS_PANE"
  - "RED_STAINED_GLASS_PANE"
  - "BLACK_STAINED_GLASS_PANE"
  - "YELLOW_STAINED_GLASS_PANE"
  - "PINK_STAINED_GLASS_PANE"
  - "ORANGE_STAINED_GLASS_PANE"
  - "PURPLE_STAINED_GLASS_PANE"